# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
default_velocity_scaling_factor: 1.0
joint_limits:
  arm_left_1_joint:
#    max_position: 1.495
#    min_position: -1.105
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_left_2_joint:
#    max_position: 1.495
#    min_position: -1.105
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_left_3_joint:
#    max_position: 3.855
#    min_position: -0.715
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_left_4_joint:
#    max_position: 2.285
#    min_position: -0.315
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_left_5_joint:
#    max_position: 2.065
#    min_position: -2.065
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_left_6_joint:
#    max_position: 1.385
#    min_position: -1.385
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_left_7_joint:
#    max_position: 2.065
#    min_position: -2.065
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_right_1_joint:
#    max_position: 1.495
#    min_position: -1.105
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_right_2_joint:
#    max_position: 1.495
#    min_position: -1.105
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_right_3_joint:
#    max_position: 3.855
#    min_position: -0.715
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_right_4_joint:
#    max_position: 2.285
#    min_position: -0.315
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_right_5_joint:
#    max_position: 2.065
#    min_position: -2.065
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_right_6_joint:
#    max_position: 1.385
#    min_position: -1.385
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: true
    max_acceleration: 10.0
  arm_right_7_joint:
#    max_position: 2.065
#    min_position: -2.065
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: true
    max_acceleration: 10.0
  # pal-gripper
  gripper_left_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.065
    has_acceleration_limits: true
    max_acceleration: 10.0
  gripper_left_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.065
    has_acceleration_limits: true
    max_acceleration: 10.0
  gripper_right_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.065
    has_acceleration_limits: true
    max_acceleration: 10.0
  gripper_right_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.065
    has_acceleration_limits: true
    max_acceleration: 10.0
  # schunk-wsg
  gripper_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: true
    max_acceleration: 10.0
  gripper_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: true
    max_acceleration: 10.0
  # pal-hey5
  hand_right_index_joint:
    has_velocity_limits: true
    max_velocity: 3.35
    has_acceleration_limits: true
    max_acceleration: 10.0
  hand_right_mrl_joint:
    has_velocity_limits: true
    max_velocity: 3.56
    has_acceleration_limits: true
    max_acceleration: 10.0
  hand_right_thumb_joint:
    has_velocity_limits: true
    max_velocity: 3.35
    has_acceleration_limits: true
    max_acceleration: 10.0
  torso_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.07000000000000001
    has_acceleration_limits: true
    max_acceleration: 10.0