planning_plugins: 
  - ompl_interface/OMPLPlanner
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - custom_planning_request_adapters/FixStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath
start_state_max_bounds_error: 0.01
fix_start_state: True
planner_configs:
  AnytimePathShorteningDefault:
    type: geometric::AnytimePathShortening
arm_left:
  planner_configs:
    - AnytimePathShorteningDefault
  projection_evaluator: joints(arm_left_1_joint,arm_left_2_joint)
  longest_valid_segment_fraction: 0.01
arm_left_torso:
  planner_configs:
    - AnytimePathShorteningDefault
  projection_evaluator: joints(torso_lift_joint,arm_left_1_joint)
  longest_valid_segment_fraction: 0.01
arm_right:
  planner_configs:
    - AnytimePathShorteningDefault
  projection_evaluator: joints(arm_right_1_joint,arm_right_2_joint)
  longest_valid_segment_fraction: 0.01
arm_right_torso:
  planner_configs:
    - AnytimePathShorteningDefault
  projection_evaluator: joints(torso_lift_joint,arm_right_1_joint)
  longest_valid_segment_fraction: 0.01
torso:
  planner_configs:
    - AnytimePathShorteningDefault
both_arms_torso:
  planner_configs:
    - AnytimePathShorteningDefault
  projection_evaluator: joints(torso_lift_joint,arm_left_1_joint)
  longest_valid_segment_fraction: 0.01
